version: '3.8'
services:
  api:
    image: api
    build: 
      context: api
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 3001:3001

  client:
    image: client
    build: 
      context: client
      dockerfile: ./Dockerfile
    container_name: client
    ports:
      - 3000:3000
    depends_on:
      - api

  